// AUTO-GENERATED by `bun run gen` (scripts/gen.ts). Do not edit by hand.
import { Elysia } from "elysia";
import { healthModule } from "./health/routes";

/** Every API module, auto-mounted. Chained statically so `typeof api` stays precise. */
export const modules = new Elysia({ name: "app-modules" })
  .use(healthModule);
