#!/usr/bin/env bun
/**
 * Codegen for the template's declarative integration points.
 *
 * Run with `bun run gen`. It regenerates three barrels by scanning the
 * filesystem, so adding a module never requires hand-editing them:
 *
 *   1. packages/database/src/schema/index.ts   — re-exports every schema file.
 *   2. packages/api/src/modules/index.ts        — mounts every API module.
 *   3. apps/web/modules/dashboard-modules.generated.ts — loads every dashboard
 *                                                  registration side-effect.
 *
 * Why codegen instead of a runtime glob? Cross-package *named* imports
 * (`import { clientes } from "@template/database"`) and Elysia's `typeof api`
 * (which Eden relies on) both need statically-analyzable exports. A runtime
 * glob cannot provide those; a generated file of plain static imports can.
 * It is also exactly the step the future CLI will run when scaffolding.
 */
import {
  existsSync,
  readFileSync,
  readdirSync,
  writeFileSync,
} from "node:fs";
import { join } from "node:path";

const ROOT = join(import.meta.dir, "..");

const HEADER =
  "// AUTO-GENERATED by `bun run gen` (scripts/gen.ts). Do not edit by hand.\n";

/** Write only if the content changed, and report what happened. */
function writeIfChanged(absPath: string, relPath: string, content: string): void {
  const current = existsSync(absPath) ? readFileSync(absPath, "utf8") : null;
  if (current === content) {
    console.log(`  = ${relPath} (unchanged)`);
    return;
  }
  writeFileSync(absPath, content);
  console.log(`  ✓ ${relPath}`);
}

/** kebab/snake folder name -> camelCase identifier. */
function toCamelCase(name: string): string {
  return name.replace(/[-_](\w)/g, (_, c: string) => c.toUpperCase());
}

function listDirs(dir: string): string[] {
  if (!existsSync(dir)) return [];
  return readdirSync(dir, { withFileTypes: true })
    .filter((e) => e.isDirectory())
    .map((e) => e.name)
    .sort();
}

// 1. Database schema barrel ---------------------------------------------------
function genSchemaBarrel(): void {
  const dir = join(ROOT, "packages/database/src/schema");
  const files = readdirSync(dir)
    .filter((f) => f.endsWith(".ts") && f !== "index.ts" && !f.endsWith(".d.ts"))
    .map((f) => f.replace(/\.ts$/, ""))
    .sort();

  const body = files.length
    ? files.map((f) => `export * from "./${f}";`).join("\n")
    : "export {};";

  const content = `${HEADER}\n${body}\n`;
  writeIfChanged(join(dir, "index.ts"), "packages/database/src/schema/index.ts", content);
}

// 2. API modules barrel -------------------------------------------------------
function genApiModules(): void {
  const dir = join(ROOT, "packages/api/src/modules");
  const modules = listDirs(dir).filter((name) =>
    existsSync(join(dir, name, "routes.ts")),
  );

  const imports = modules
    .map((name) => `import { ${toCamelCase(name)}Module } from "./${name}/routes";`)
    .join("\n");

  const chain = modules.length
    ? modules.map((name) => `  .use(${toCamelCase(name)}Module)`).join("\n")
    : "";

  const content =
    `${HEADER}` +
    `import { Elysia } from "elysia";\n` +
    (imports ? `${imports}\n` : "") +
    `\n/** Every API module, auto-mounted. Chained statically so \`typeof api\` stays precise. */\n` +
    `export const modules = new Elysia({ name: "app-modules" })${chain ? `\n${chain}` : ""};\n`;

  writeIfChanged(join(dir, "index.ts"), "packages/api/src/modules/index.ts", content);
}

// 3. Frontend dashboard registration manifest ---------------------------------
function genDashboardManifest(): void {
  const dir = join(ROOT, "apps/web/modules");
  const modules = listDirs(dir).filter((name) =>
    existsSync(join(dir, name, "dashboard.ts")),
  );

  const sideEffects = modules.map((name) => `import "./${name}/dashboard";`).join("\n");

  const content =
    `${HEADER}` +
    (sideEffects ? `${sideEffects}\n` : "") +
    `\nexport { getDashboardModules } from "./dashboard/data/dashboard-sidebar-data";\n`;

  writeIfChanged(
    join(dir, "dashboard-modules.generated.ts"),
    "apps/web/modules/dashboard-modules.generated.ts",
    content,
  );
}

console.log("Generating declarative barrels…");
genSchemaBarrel();
genApiModules();
genDashboardManifest();
console.log("Done.");
