// AUTO-GENERATED by `bun run gen` (scripts/gen.ts). Do not edit by hand.
import "./clientes/dashboard";
import "./dashboard/dashboard";

export { getDashboardModules } from "./dashboard/data/dashboard-sidebar-data";
